// Mocks generated by Mockito 5.4.6 from annotations
// in petkeeperlite/test/src/modules/pet/domain/usecases/pet_usecases_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:io' as _i6;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:petkeeperlite/src/modules/pet/domain/entities/pet_entity.dart'
    as _i2;
import 'package:petkeeperlite/src/modules/pet/domain/entities/pet_task_entity.dart'
    as _i3;
import 'package:petkeeperlite/src/modules/pet/domain/repositories/pet_repository.dart'
    as _i4;
import 'package:petkeeperlite/src/modules/pet/domain/repositories/pet_task_repository.dart'
    as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakePetEntity_0 extends _i1.SmartFake implements _i2.PetEntity {
  _FakePetEntity_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePetTaskEntity_1 extends _i1.SmartFake implements _i3.PetTaskEntity {
  _FakePetTaskEntity_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [PetRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockPetRepository extends _i1.Mock implements _i4.PetRepository {
  @override
  _i5.Stream<List<_i2.PetEntity>> watchPets(String? familyCode) =>
      (super.noSuchMethod(
            Invocation.method(#watchPets, [familyCode]),
            returnValue: _i5.Stream<List<_i2.PetEntity>>.empty(),
            returnValueForMissingStub: _i5.Stream<List<_i2.PetEntity>>.empty(),
          )
          as _i5.Stream<List<_i2.PetEntity>>);

  @override
  _i5.Future<_i2.PetEntity?> getPet(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getPet, [id]),
            returnValue: _i5.Future<_i2.PetEntity?>.value(),
            returnValueForMissingStub: _i5.Future<_i2.PetEntity?>.value(),
          )
          as _i5.Future<_i2.PetEntity?>);

  @override
  _i5.Future<_i2.PetEntity> addPet(_i2.PetEntity? pet) =>
      (super.noSuchMethod(
            Invocation.method(#addPet, [pet]),
            returnValue: _i5.Future<_i2.PetEntity>.value(
              _FakePetEntity_0(this, Invocation.method(#addPet, [pet])),
            ),
            returnValueForMissingStub: _i5.Future<_i2.PetEntity>.value(
              _FakePetEntity_0(this, Invocation.method(#addPet, [pet])),
            ),
          )
          as _i5.Future<_i2.PetEntity>);

  @override
  _i5.Future<_i2.PetEntity> updatePet(_i2.PetEntity? pet) =>
      (super.noSuchMethod(
            Invocation.method(#updatePet, [pet]),
            returnValue: _i5.Future<_i2.PetEntity>.value(
              _FakePetEntity_0(this, Invocation.method(#updatePet, [pet])),
            ),
            returnValueForMissingStub: _i5.Future<_i2.PetEntity>.value(
              _FakePetEntity_0(this, Invocation.method(#updatePet, [pet])),
            ),
          )
          as _i5.Future<_i2.PetEntity>);

  @override
  _i5.Future<void> deletePet(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deletePet, [id]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<String> uploadImage(_i6.File? file, String? filename) =>
      (super.noSuchMethod(
            Invocation.method(#uploadImage, [file, filename]),
            returnValue: _i5.Future<String>.value(
              _i7.dummyValue<String>(
                this,
                Invocation.method(#uploadImage, [file, filename]),
              ),
            ),
            returnValueForMissingStub: _i5.Future<String>.value(
              _i7.dummyValue<String>(
                this,
                Invocation.method(#uploadImage, [file, filename]),
              ),
            ),
          )
          as _i5.Future<String>);
}

/// A class which mocks [PetTaskRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockPetTaskRepository extends _i1.Mock implements _i8.PetTaskRepository {
  @override
  _i5.Stream<List<_i3.PetTaskEntity>> watchTasks(String? petId) =>
      (super.noSuchMethod(
            Invocation.method(#watchTasks, [petId]),
            returnValue: _i5.Stream<List<_i3.PetTaskEntity>>.empty(),
            returnValueForMissingStub:
                _i5.Stream<List<_i3.PetTaskEntity>>.empty(),
          )
          as _i5.Stream<List<_i3.PetTaskEntity>>);

  @override
  _i5.Future<_i3.PetTaskEntity> addTask(_i3.PetTaskEntity? task) =>
      (super.noSuchMethod(
            Invocation.method(#addTask, [task]),
            returnValue: _i5.Future<_i3.PetTaskEntity>.value(
              _FakePetTaskEntity_1(this, Invocation.method(#addTask, [task])),
            ),
            returnValueForMissingStub: _i5.Future<_i3.PetTaskEntity>.value(
              _FakePetTaskEntity_1(this, Invocation.method(#addTask, [task])),
            ),
          )
          as _i5.Future<_i3.PetTaskEntity>);

  @override
  _i5.Future<_i3.PetTaskEntity> updateTask(_i3.PetTaskEntity? task) =>
      (super.noSuchMethod(
            Invocation.method(#updateTask, [task]),
            returnValue: _i5.Future<_i3.PetTaskEntity>.value(
              _FakePetTaskEntity_1(
                this,
                Invocation.method(#updateTask, [task]),
              ),
            ),
            returnValueForMissingStub: _i5.Future<_i3.PetTaskEntity>.value(
              _FakePetTaskEntity_1(
                this,
                Invocation.method(#updateTask, [task]),
              ),
            ),
          )
          as _i5.Future<_i3.PetTaskEntity>);

  @override
  _i5.Future<void> deleteTask(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteTask, [id]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}
