// Mocks generated by Mockito 5.4.6 from annotations
// in petkeeperlite/test/src/modules/pet/domain/usecases/update_task_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:petkeeperlite/src/modules/pet/domain/entities/pet_task_entity.dart'
    as _i2;
import 'package:petkeeperlite/src/modules/pet/domain/repositories/pet_task_repository.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakePetTaskEntity_0 extends _i1.SmartFake implements _i2.PetTaskEntity {
  _FakePetTaskEntity_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [PetTaskRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockPetTaskRepository extends _i1.Mock implements _i3.PetTaskRepository {
  @override
  _i4.Stream<List<_i2.PetTaskEntity>> watchTasks(String? petId) =>
      (super.noSuchMethod(
            Invocation.method(#watchTasks, [petId]),
            returnValue: _i4.Stream<List<_i2.PetTaskEntity>>.empty(),
            returnValueForMissingStub:
                _i4.Stream<List<_i2.PetTaskEntity>>.empty(),
          )
          as _i4.Stream<List<_i2.PetTaskEntity>>);

  @override
  _i4.Future<_i2.PetTaskEntity> addTask(_i2.PetTaskEntity? task) =>
      (super.noSuchMethod(
            Invocation.method(#addTask, [task]),
            returnValue: _i4.Future<_i2.PetTaskEntity>.value(
              _FakePetTaskEntity_0(this, Invocation.method(#addTask, [task])),
            ),
            returnValueForMissingStub: _i4.Future<_i2.PetTaskEntity>.value(
              _FakePetTaskEntity_0(this, Invocation.method(#addTask, [task])),
            ),
          )
          as _i4.Future<_i2.PetTaskEntity>);

  @override
  _i4.Future<_i2.PetTaskEntity> updateTask(_i2.PetTaskEntity? task) =>
      (super.noSuchMethod(
            Invocation.method(#updateTask, [task]),
            returnValue: _i4.Future<_i2.PetTaskEntity>.value(
              _FakePetTaskEntity_0(
                this,
                Invocation.method(#updateTask, [task]),
              ),
            ),
            returnValueForMissingStub: _i4.Future<_i2.PetTaskEntity>.value(
              _FakePetTaskEntity_0(
                this,
                Invocation.method(#updateTask, [task]),
              ),
            ),
          )
          as _i4.Future<_i2.PetTaskEntity>);

  @override
  _i4.Future<void> deleteTask(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteTask, [id]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
